### PR TITLE
Passed options on to base constructor

### PR DESCRIPTION
**Pull request by wexman**
The existing code works fine when used with streams, but when "manually" writing image data from a buffer this doesn't work because the options aren't passed to the base constructor...

### CODE REVIEW

**Comment by devongovett** [comment]
What options are you passing?

**Comment by wexman** [comment]
I'm passing the usual encoder options: width, height and colorSpace. Here's a small example: 

var encoder = pics.encode('image/png', { width: img.width, height: img.height, colorSpace: 'rgba' });
var file = fs.createWriteStream(filename);
var buf = new Buffer(img.data);
encoder.write(buf);
encoder.pipe(file);

Without the modification, this won't work...

**Comment by devongovett** [comment]
Thanks! Also make sure you call `encoder.end()` there as well or the stream will never end.

**Comment by wexman** [comment]
Ok, thanks! I'm actually quite new to nodejs so I am grateful for every help I get!

**Pull request merged**
